import Head from 'next/head'
import Link from 'next/link'
import { useState } from 'react'
import { useAppDispatch } from '@/hooks/useAppDispatch'
import { setUserMode, UserMode } from '@/store/genieSlice'
import { useRouter } from 'next/router'

export default function Home() {
  const [hoveredMode, setHoveredMode] = useState<UserMode | null>(null)
  const dispatch = useAppDispatch()
  const router = useRouter()

  const handleModeSelect = (mode: UserMode) => {
    dispatch(setUserMode(mode))
    router.push(mode === 'learner' ? '/learn' : '/create')
  }

  return (
    <>
      <Head>
        <title>CodeVideo Genie - AI-Powered Programming Tutorials</title>
        <meta name="description" content="Learn any programming concept with personalized video tutorials generated by AI in seconds." />
      </Head>

      {/* Hero Section */}
      <section className="relative min-h-screen flex items-center justify-center overflow-hidden pt-16">
        {/* Background effects */}
        <div className="absolute inset-0 bg-genie-glow opacity-30" />
        <div className="absolute top-1/4 left-1/4 w-96 h-96 bg-purple-500/20 rounded-full blur-3xl" />
        <div className="absolute bottom-1/4 right-1/4 w-96 h-96 bg-pink-500/20 rounded-full blur-3xl" />
        
        <div className="relative z-10 max-w-6xl mx-auto px-4 text-center">
          {/* Badge */}
          <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-gray-800/50 border border-gray-700 mb-8">
            <span className="text-xl">✨</span>
            <span className="text-sm text-gray-300">AI-Powered Learning</span>
          </div>

          {/* Main headline */}
          <h1 className="text-5xl md:text-7xl font-bold mb-6 leading-tight">
            Learn to code with{' '}
            <span className="genie-text">your personal</span>
            <br />
            <span className="genie-text">AI tutor</span>
          </h1>

          <p className="text-xl text-gray-400 max-w-2xl mx-auto mb-16">
            Generate personalized programming tutorials in seconds. 
            Whether you&apos;re learning or teaching, Genie creates exactly what you need.
          </p>

          {/* Mode Selection Cards */}
          <div className="grid md:grid-cols-2 gap-8 max-w-4xl mx-auto">
            {/* Learner Card */}
            <button
              onClick={() => handleModeSelect('learner')}
              onMouseEnter={() => setHoveredMode('learner')}
              onMouseLeave={() => setHoveredMode(null)}
              className={`group relative p-8 rounded-2xl text-left transition-all duration-500 card-hover ${
                hoveredMode === 'learner' 
                  ? 'bg-gradient-to-br from-purple-900/50 to-purple-800/30 border-purple-500/50' 
                  : 'bg-gray-900/50 border-gray-700/50'
              } border`}
            >
              <div className={`absolute inset-0 rounded-2xl bg-gradient-to-br from-purple-500/20 to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-500`} />
              
              <div className="relative z-10">
                <div className="text-5xl mb-4">🎓</div>
                <h2 className="text-2xl font-bold mb-3 text-white">I want to Learn</h2>
                <p className="text-gray-400 mb-6">
                  Tell us what you want to learn. We&apos;ll create a personalized tutorial 
                  tailored to your experience level and learning style.
                </p>
                <ul className="space-y-2 text-sm text-gray-500">
                  <li className="flex items-center gap-2">
                    <span className="text-purple-400">✓</span>
                    Personalized to your skill level
                  </li>
                  <li className="flex items-center gap-2">
                    <span className="text-purple-400">✓</span>
                    Multiple learning styles
                  </li>
                  <li className="flex items-center gap-2">
                    <span className="text-purple-400">✓</span>
                    Any programming topic
                  </li>
                </ul>
              </div>

              <div className={`absolute bottom-6 right-6 text-purple-400 transition-transform duration-300 ${
                hoveredMode === 'learner' ? 'translate-x-1' : ''
              }`}>
                →
              </div>
            </button>

            {/* Creator Card */}
            <button
              onClick={() => handleModeSelect('creator')}
              onMouseEnter={() => setHoveredMode('creator')}
              onMouseLeave={() => setHoveredMode(null)}
              className={`group relative p-8 rounded-2xl text-left transition-all duration-500 card-hover ${
                hoveredMode === 'creator' 
                  ? 'bg-gradient-to-br from-pink-900/50 to-pink-800/30 border-pink-500/50' 
                  : 'bg-gray-900/50 border-gray-700/50'
              } border`}
            >
              <div className={`absolute inset-0 rounded-2xl bg-gradient-to-br from-pink-500/20 to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-500`} />
              
              <div className="relative z-10">
                <div className="text-5xl mb-4">🛠️</div>
                <h2 className="text-2xl font-bold mb-3 text-white">I want to Create</h2>
                <p className="text-gray-400 mb-6">
                  Build courses, tutorials, and educational content. 
                  AI generates the structure, you refine and publish.
                </p>
                <ul className="space-y-2 text-sm text-gray-500">
                  <li className="flex items-center gap-2">
                    <span className="text-pink-400">✓</span>
                    AI-assisted course creation
                  </li>
                  <li className="flex items-center gap-2">
                    <span className="text-pink-400">✓</span>
                    Export to video, markdown, PDF
                  </li>
                  <li className="flex items-center gap-2">
                    <span className="text-pink-400">✓</span>
                    Validated, working code
                  </li>
                </ul>
              </div>

              <div className={`absolute bottom-6 right-6 text-pink-400 transition-transform duration-300 ${
                hoveredMode === 'creator' ? 'translate-x-1' : ''
              }`}>
                →
              </div>
            </button>
          </div>

          {/* Quick stats */}
          <div className="mt-20 grid grid-cols-3 gap-8 max-w-2xl mx-auto">
            <div className="text-center">
              <div className="text-3xl font-bold genie-text">30s</div>
              <div className="text-sm text-gray-500">Generation time</div>
            </div>
            <div className="text-center">
              <div className="text-3xl font-bold genie-text">∞</div>
              <div className="text-sm text-gray-500">Topics covered</div>
            </div>
            <div className="text-center">
              <div className="text-3xl font-bold genie-text">100%</div>
              <div className="text-sm text-gray-500">Personalized</div>
            </div>
          </div>
        </div>
      </section>

      {/* How it works */}
      <section className="py-24 bg-gray-900/30">
        <div className="max-w-6xl mx-auto px-4">
          <h2 className="text-4xl font-bold text-center mb-4">
            How it <span className="genie-text">works</span>
          </h2>
          <p className="text-gray-400 text-center mb-16 max-w-2xl mx-auto">
            From idea to tutorial in three simple steps
          </p>

          <div className="grid md:grid-cols-3 gap-8">
            <div className="text-center">
              <div className="w-16 h-16 rounded-full bg-purple-500/20 flex items-center justify-center mx-auto mb-6">
                <span className="text-2xl">1</span>
              </div>
              <h3 className="text-xl font-semibold mb-3">Describe</h3>
              <p className="text-gray-400">
                Tell Genie what you want to learn or teach in plain English
              </p>
            </div>

            <div className="text-center">
              <div className="w-16 h-16 rounded-full bg-pink-500/20 flex items-center justify-center mx-auto mb-6">
                <span className="text-2xl">2</span>
              </div>
              <h3 className="text-xl font-semibold mb-3">Generate</h3>
              <p className="text-gray-400">
                AI creates a step-by-step tutorial with validated, working code
              </p>
            </div>

            <div className="text-center">
              <div className="w-16 h-16 rounded-full bg-cyan-500/20 flex items-center justify-center mx-auto mb-6">
                <span className="text-2xl">3</span>
              </div>
              <h3 className="text-xl font-semibold mb-3">Learn or Export</h3>
              <p className="text-gray-400">
                Step through interactively, or export as video, markdown, or PDF
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* CTA */}
      <section className="py-24">
        <div className="max-w-4xl mx-auto px-4 text-center">
          <h2 className="text-4xl font-bold mb-6">
            Ready to start <span className="genie-text">learning</span>?
          </h2>
          <p className="text-xl text-gray-400 mb-8">
            3 free generations per month. No credit card required.
          </p>
          <div className="flex gap-4 justify-center">
            <Link href="/learn" className="btn-primary text-lg px-8 py-4">
              Start Learning Free
            </Link>
            <Link href="/pricing" className="btn-secondary text-lg px-8 py-4">
              View Pricing
            </Link>
          </div>
        </div>
      </section>
    </>
  )
}
